<a href="https://colab.research.google.com/github/223T1A3112/addition-of-matrix/blob/main/addtion_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense


In [3]:

import numpy as np

matrix = np.array([1,2,3],[4,5,6])

print(matrix)


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [8]:

import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
def add_matrices(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrices must have the same dimensions")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)

    return result

matrix1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix2 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result = add_matrices(matrix1, matrix2)
for row in result:
    print(row)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [9]:
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix C (A multiplied by B):")
print(C)



Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix C (A multiplied by B):
[[19 22]
 [43 50]]
