<a href="https://colab.research.google.com/github/223T1A3112/addition-of-matrix/blob/main/division.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define two matrices
matrix1 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matrix2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Perform element-wise division
result = matrix1 / matrix2

print(result)


[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
